# Generated by Django 4.1 on 2022-10-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='karya_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
