# Generated by Django 4.1 on 2022-10-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arti', '0002_alter_karya_karya_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karya',
            old_name='karya_image',
            new_name='gambar',
        ),
    ]
