# Generated by Django 4.1 on 2022-10-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti', '0002_alter_karya_karya_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='karya',
            name='harga',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
