# Generated by Django 4.1 on 2022-10-29 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arti', '0004_rename_karya_image_karya_gambar_karya_deskripsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karya',
            name='tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
