# Generated by Django 4.1 on 2022-10-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti', '0006_userarti'),
    ]

    operations = [
        migrations.AddField(
            model_name='karya',
            name='kategori',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
