# Generated by Django 4.1 on 2022-10-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti', '0008_auto_20221030_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='deskripsi',
            field=models.BigIntegerField(),
        ),
    ]
