# Generated by Django 4.1 on 2022-10-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='user',
        ),
    ]
