# Generated by Django 4.1 on 2022-10-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0002_uploadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='caption',
        ),
    ]
